name: Pull request
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
      - mmackz/test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  verify-config-file-format:
    name: Verify Config File Format
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags, consider using a specific number for performance

      - name: Fetch target branch
        run: git fetch origin mmackz/test:mmackz/test

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run config file format verification script
        run: npx ts-node ./.github/scripts/verifyConfigFileFormat.ts
